server:
  port: 9191

spring:
  application:
    name: API-GATWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"  
      routes:
      - id: AUTHENTICATION-SERVICE
        uri: lb://AUTHENTICATION-SERVICE
        predicates:
        - Path=/api/auth/**
      - id: PRODUCT1-SERVICE 
        uri: lb://PRODUCT1-SERVICE 
        predicates:
        - Path=/product/**          



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
   